// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: backchannel/broadcast.proto

package backchannelpb

import (
	clientchannelpb "github.com/fraym-work/streams-proto/go/v6/clientchannelpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic     string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Broadcast bool                   `protobuf:"varint,3,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Event     *clientchannelpb.Event `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backchannel_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backchannel_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_backchannel_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BroadcastRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BroadcastRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *BroadcastRequest) GetEvent() *clientchannelpb.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*BroadcastResponse_BroadcastAck
	//	*BroadcastResponse_BroadcastNotAck
	Payload isBroadcastResponse_Payload `protobuf_oneof:"payload"`
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backchannel_broadcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backchannel_broadcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_backchannel_broadcast_proto_rawDescGZIP(), []int{1}
}

func (m *BroadcastResponse) GetPayload() isBroadcastResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *BroadcastResponse) GetBroadcastAck() *BroadcastResponse_Broadcast_Ack {
	if x, ok := x.GetPayload().(*BroadcastResponse_BroadcastAck); ok {
		return x.BroadcastAck
	}
	return nil
}

func (x *BroadcastResponse) GetBroadcastNotAck() *BroadcastResponse_Broadcast_NotAck {
	if x, ok := x.GetPayload().(*BroadcastResponse_BroadcastNotAck); ok {
		return x.BroadcastNotAck
	}
	return nil
}

type isBroadcastResponse_Payload interface {
	isBroadcastResponse_Payload()
}

type BroadcastResponse_BroadcastAck struct {
	BroadcastAck *BroadcastResponse_Broadcast_Ack `protobuf:"bytes,1,opt,name=broadcast_ack,json=broadcastAck,proto3,oneof"`
}

type BroadcastResponse_BroadcastNotAck struct {
	BroadcastNotAck *BroadcastResponse_Broadcast_NotAck `protobuf:"bytes,2,opt,name=broadcast_not_ack,json=broadcastNotAck,proto3,oneof"`
}

func (*BroadcastResponse_BroadcastAck) isBroadcastResponse_Payload() {}

func (*BroadcastResponse_BroadcastNotAck) isBroadcastResponse_Payload() {}

type BroadcastResponse_Broadcast_Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BroadcastResponse_Broadcast_Ack) Reset() {
	*x = BroadcastResponse_Broadcast_Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backchannel_broadcast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastResponse_Broadcast_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse_Broadcast_Ack) ProtoMessage() {}

func (x *BroadcastResponse_Broadcast_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_backchannel_broadcast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse_Broadcast_Ack.ProtoReflect.Descriptor instead.
func (*BroadcastResponse_Broadcast_Ack) Descriptor() ([]byte, []int) {
	return file_backchannel_broadcast_proto_rawDescGZIP(), []int{1, 0}
}

type BroadcastResponse_Broadcast_NotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BroadcastResponse_Broadcast_NotAck) Reset() {
	*x = BroadcastResponse_Broadcast_NotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backchannel_broadcast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastResponse_Broadcast_NotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse_Broadcast_NotAck) ProtoMessage() {}

func (x *BroadcastResponse_Broadcast_NotAck) ProtoReflect() protoreflect.Message {
	mi := &file_backchannel_broadcast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse_Broadcast_NotAck.ProtoReflect.Descriptor instead.
func (*BroadcastResponse_Broadcast_NotAck) Descriptor() ([]byte, []int) {
	return file_backchannel_broadcast_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BroadcastResponse_Broadcast_NotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_backchannel_broadcast_proto protoreflect.FileDescriptor

var file_backchannel_broadcast_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x61, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62,
	0x61, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x19, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x8f, 0x02, 0x0a, 0x11, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x0d, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x5f, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x41, 0x63, 0x6b, 0x12, 0x5d, 0x0a, 0x11, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4e, 0x6f, 0x74,
	0x41, 0x63, 0x6b, 0x1a, 0x0f, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x5f, 0x41, 0x63, 0x6b, 0x1a, 0x2a, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x5f, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_backchannel_broadcast_proto_rawDescOnce sync.Once
	file_backchannel_broadcast_proto_rawDescData = file_backchannel_broadcast_proto_rawDesc
)

func file_backchannel_broadcast_proto_rawDescGZIP() []byte {
	file_backchannel_broadcast_proto_rawDescOnce.Do(func() {
		file_backchannel_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_backchannel_broadcast_proto_rawDescData)
	})
	return file_backchannel_broadcast_proto_rawDescData
}

var file_backchannel_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backchannel_broadcast_proto_goTypes = []interface{}{
	(*BroadcastRequest)(nil),                   // 0: backchannel.BroadcastRequest
	(*BroadcastResponse)(nil),                  // 1: backchannel.BroadcastResponse
	(*BroadcastResponse_Broadcast_Ack)(nil),    // 2: backchannel.BroadcastResponse.Broadcast_Ack
	(*BroadcastResponse_Broadcast_NotAck)(nil), // 3: backchannel.BroadcastResponse.Broadcast_NotAck
	(*clientchannelpb.Event)(nil),              // 4: Event
}
var file_backchannel_broadcast_proto_depIdxs = []int32{
	4, // 0: backchannel.BroadcastRequest.event:type_name -> Event
	2, // 1: backchannel.BroadcastResponse.broadcast_ack:type_name -> backchannel.BroadcastResponse.Broadcast_Ack
	3, // 2: backchannel.BroadcastResponse.broadcast_not_ack:type_name -> backchannel.BroadcastResponse.Broadcast_NotAck
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_backchannel_broadcast_proto_init() }
func file_backchannel_broadcast_proto_init() {
	if File_backchannel_broadcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backchannel_broadcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backchannel_broadcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backchannel_broadcast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastResponse_Broadcast_Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backchannel_broadcast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastResponse_Broadcast_NotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backchannel_broadcast_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*BroadcastResponse_BroadcastAck)(nil),
		(*BroadcastResponse_BroadcastNotAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backchannel_broadcast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backchannel_broadcast_proto_goTypes,
		DependencyIndexes: file_backchannel_broadcast_proto_depIdxs,
		MessageInfos:      file_backchannel_broadcast_proto_msgTypes,
	}.Build()
	File_backchannel_broadcast_proto = out.File
	file_backchannel_broadcast_proto_rawDesc = nil
	file_backchannel_broadcast_proto_goTypes = nil
	file_backchannel_broadcast_proto_depIdxs = nil
}
