// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: clientchannel/response.proto

package clientchannelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Response_Event
	//	*Response_InitAck_
	//	*Response_InitNotAck_
	//	*Response_PublishAck_
	//	*Response_PublishNotAck_
	//	*Response_SubscribeAck_
	//	*Response_SubscribeNotAck_
	//	*Response_SnapshotStarted_
	//	*Response_SnapshotNotStarted_
	//	*Response_SnapshotFinished_
	//	*Response_SnapshotNotFinished_
	//	*Response_InvalidateGdprAck_
	//	*Response_InvalidateGdprNotAck_
	//	*Response_IntroduceGdprOnFieldStarted_
	//	*Response_IntroduceGdprOnFieldNotStarted_
	//	*Response_IntroduceGdprOnFieldFinished_
	//	*Response_IntroduceGdprOnFieldNotFinished_
	Data isResponse_Data `protobuf_oneof:"data"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0}
}

func (m *Response) GetData() isResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Response) GetEvent() *PublishEventEnvelope {
	if x, ok := x.GetData().(*Response_Event); ok {
		return x.Event
	}
	return nil
}

func (x *Response) GetInitAck() *Response_InitAck {
	if x, ok := x.GetData().(*Response_InitAck_); ok {
		return x.InitAck
	}
	return nil
}

func (x *Response) GetInitNotAck() *Response_InitNotAck {
	if x, ok := x.GetData().(*Response_InitNotAck_); ok {
		return x.InitNotAck
	}
	return nil
}

func (x *Response) GetPublishAck() *Response_PublishAck {
	if x, ok := x.GetData().(*Response_PublishAck_); ok {
		return x.PublishAck
	}
	return nil
}

func (x *Response) GetPublishNotAck() *Response_PublishNotAck {
	if x, ok := x.GetData().(*Response_PublishNotAck_); ok {
		return x.PublishNotAck
	}
	return nil
}

func (x *Response) GetSubscribeAck() *Response_SubscribeAck {
	if x, ok := x.GetData().(*Response_SubscribeAck_); ok {
		return x.SubscribeAck
	}
	return nil
}

func (x *Response) GetSubscribeNotAck() *Response_SubscribeNotAck {
	if x, ok := x.GetData().(*Response_SubscribeNotAck_); ok {
		return x.SubscribeNotAck
	}
	return nil
}

func (x *Response) GetSnapshotStarted() *Response_SnapshotStarted {
	if x, ok := x.GetData().(*Response_SnapshotStarted_); ok {
		return x.SnapshotStarted
	}
	return nil
}

func (x *Response) GetSnapshotNotStarted() *Response_SnapshotNotStarted {
	if x, ok := x.GetData().(*Response_SnapshotNotStarted_); ok {
		return x.SnapshotNotStarted
	}
	return nil
}

func (x *Response) GetSnapshotFinished() *Response_SnapshotFinished {
	if x, ok := x.GetData().(*Response_SnapshotFinished_); ok {
		return x.SnapshotFinished
	}
	return nil
}

func (x *Response) GetSnapshotNotFinished() *Response_SnapshotNotFinished {
	if x, ok := x.GetData().(*Response_SnapshotNotFinished_); ok {
		return x.SnapshotNotFinished
	}
	return nil
}

func (x *Response) GetInvalidateGdprAck() *Response_InvalidateGdprAck {
	if x, ok := x.GetData().(*Response_InvalidateGdprAck_); ok {
		return x.InvalidateGdprAck
	}
	return nil
}

func (x *Response) GetInvalidateGdprNotAck() *Response_InvalidateGdprNotAck {
	if x, ok := x.GetData().(*Response_InvalidateGdprNotAck_); ok {
		return x.InvalidateGdprNotAck
	}
	return nil
}

func (x *Response) GetIntroduceGdprOnFieldStarted() *Response_IntroduceGdprOnFieldStarted {
	if x, ok := x.GetData().(*Response_IntroduceGdprOnFieldStarted_); ok {
		return x.IntroduceGdprOnFieldStarted
	}
	return nil
}

func (x *Response) GetIntroduceGdprOnFieldNotStarted() *Response_IntroduceGdprOnFieldNotStarted {
	if x, ok := x.GetData().(*Response_IntroduceGdprOnFieldNotStarted_); ok {
		return x.IntroduceGdprOnFieldNotStarted
	}
	return nil
}

func (x *Response) GetIntroduceGdprOnFieldFinished() *Response_IntroduceGdprOnFieldFinished {
	if x, ok := x.GetData().(*Response_IntroduceGdprOnFieldFinished_); ok {
		return x.IntroduceGdprOnFieldFinished
	}
	return nil
}

func (x *Response) GetIntroduceGdprOnFieldNotFinished() *Response_IntroduceGdprOnFieldNotFinished {
	if x, ok := x.GetData().(*Response_IntroduceGdprOnFieldNotFinished_); ok {
		return x.IntroduceGdprOnFieldNotFinished
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_Event struct {
	Event *PublishEventEnvelope `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type Response_InitAck_ struct {
	InitAck *Response_InitAck `protobuf:"bytes,2,opt,name=init_ack,json=initAck,proto3,oneof"`
}

type Response_InitNotAck_ struct {
	InitNotAck *Response_InitNotAck `protobuf:"bytes,3,opt,name=init_not_ack,json=initNotAck,proto3,oneof"`
}

type Response_PublishAck_ struct {
	PublishAck *Response_PublishAck `protobuf:"bytes,4,opt,name=publish_ack,json=publishAck,proto3,oneof"`
}

type Response_PublishNotAck_ struct {
	PublishNotAck *Response_PublishNotAck `protobuf:"bytes,5,opt,name=publish_not_ack,json=publishNotAck,proto3,oneof"`
}

type Response_SubscribeAck_ struct {
	SubscribeAck *Response_SubscribeAck `protobuf:"bytes,6,opt,name=subscribe_ack,json=subscribeAck,proto3,oneof"`
}

type Response_SubscribeNotAck_ struct {
	SubscribeNotAck *Response_SubscribeNotAck `protobuf:"bytes,7,opt,name=subscribe_not_ack,json=subscribeNotAck,proto3,oneof"`
}

type Response_SnapshotStarted_ struct {
	SnapshotStarted *Response_SnapshotStarted `protobuf:"bytes,8,opt,name=snapshot_started,json=snapshotStarted,proto3,oneof"`
}

type Response_SnapshotNotStarted_ struct {
	SnapshotNotStarted *Response_SnapshotNotStarted `protobuf:"bytes,9,opt,name=snapshot_not_started,json=snapshotNotStarted,proto3,oneof"`
}

type Response_SnapshotFinished_ struct {
	SnapshotFinished *Response_SnapshotFinished `protobuf:"bytes,10,opt,name=snapshot_finished,json=snapshotFinished,proto3,oneof"`
}

type Response_SnapshotNotFinished_ struct {
	SnapshotNotFinished *Response_SnapshotNotFinished `protobuf:"bytes,11,opt,name=snapshot_not_finished,json=snapshotNotFinished,proto3,oneof"`
}

type Response_InvalidateGdprAck_ struct {
	InvalidateGdprAck *Response_InvalidateGdprAck `protobuf:"bytes,12,opt,name=invalidate_gdpr_ack,json=invalidateGdprAck,proto3,oneof"`
}

type Response_InvalidateGdprNotAck_ struct {
	InvalidateGdprNotAck *Response_InvalidateGdprNotAck `protobuf:"bytes,13,opt,name=invalidate_gdpr_not_ack,json=invalidateGdprNotAck,proto3,oneof"`
}

type Response_IntroduceGdprOnFieldStarted_ struct {
	IntroduceGdprOnFieldStarted *Response_IntroduceGdprOnFieldStarted `protobuf:"bytes,14,opt,name=introduce_gdpr_on_field_started,json=introduceGdprOnFieldStarted,proto3,oneof"`
}

type Response_IntroduceGdprOnFieldNotStarted_ struct {
	IntroduceGdprOnFieldNotStarted *Response_IntroduceGdprOnFieldNotStarted `protobuf:"bytes,15,opt,name=introduce_gdpr_on_field_not_started,json=introduceGdprOnFieldNotStarted,proto3,oneof"`
}

type Response_IntroduceGdprOnFieldFinished_ struct {
	IntroduceGdprOnFieldFinished *Response_IntroduceGdprOnFieldFinished `protobuf:"bytes,16,opt,name=introduce_gdpr_on_field_finished,json=introduceGdprOnFieldFinished,proto3,oneof"`
}

type Response_IntroduceGdprOnFieldNotFinished_ struct {
	IntroduceGdprOnFieldNotFinished *Response_IntroduceGdprOnFieldNotFinished `protobuf:"bytes,17,opt,name=introduce_gdpr_on_field_not_finished,json=introduceGdprOnFieldNotFinished,proto3,oneof"`
}

func (*Response_Event) isResponse_Data() {}

func (*Response_InitAck_) isResponse_Data() {}

func (*Response_InitNotAck_) isResponse_Data() {}

func (*Response_PublishAck_) isResponse_Data() {}

func (*Response_PublishNotAck_) isResponse_Data() {}

func (*Response_SubscribeAck_) isResponse_Data() {}

func (*Response_SubscribeNotAck_) isResponse_Data() {}

func (*Response_SnapshotStarted_) isResponse_Data() {}

func (*Response_SnapshotNotStarted_) isResponse_Data() {}

func (*Response_SnapshotFinished_) isResponse_Data() {}

func (*Response_SnapshotNotFinished_) isResponse_Data() {}

func (*Response_InvalidateGdprAck_) isResponse_Data() {}

func (*Response_InvalidateGdprNotAck_) isResponse_Data() {}

func (*Response_IntroduceGdprOnFieldStarted_) isResponse_Data() {}

func (*Response_IntroduceGdprOnFieldNotStarted_) isResponse_Data() {}

func (*Response_IntroduceGdprOnFieldFinished_) isResponse_Data() {}

func (*Response_IntroduceGdprOnFieldNotFinished_) isResponse_Data() {}

type Response_InitAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response_InitAck) Reset() {
	*x = Response_InitAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_InitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_InitAck) ProtoMessage() {}

func (x *Response_InitAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_InitAck.ProtoReflect.Descriptor instead.
func (*Response_InitAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 0}
}

type Response_InitNotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_InitNotAck) Reset() {
	*x = Response_InitNotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_InitNotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_InitNotAck) ProtoMessage() {}

func (x *Response_InitNotAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_InitNotAck.ProtoReflect.Descriptor instead.
func (*Response_InitNotAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Response_InitNotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_PublishAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublishActionId string `protobuf:"bytes,1,opt,name=publish_action_id,json=publishActionId,proto3" json:"publish_action_id,omitempty"`
}

func (x *Response_PublishAck) Reset() {
	*x = Response_PublishAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_PublishAck) ProtoMessage() {}

func (x *Response_PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_PublishAck.ProtoReflect.Descriptor instead.
func (*Response_PublishAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Response_PublishAck) GetPublishActionId() string {
	if x != nil {
		return x.PublishActionId
	}
	return ""
}

type Response_PublishNotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublishActionId string `protobuf:"bytes,1,opt,name=publish_action_id,json=publishActionId,proto3" json:"publish_action_id,omitempty"`
	Reason          string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_PublishNotAck) Reset() {
	*x = Response_PublishNotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_PublishNotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_PublishNotAck) ProtoMessage() {}

func (x *Response_PublishNotAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_PublishNotAck.ProtoReflect.Descriptor instead.
func (*Response_PublishNotAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Response_PublishNotAck) GetPublishActionId() string {
	if x != nil {
		return x.PublishActionId
	}
	return ""
}

func (x *Response_PublishNotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_SubscribeAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response_SubscribeAck) Reset() {
	*x = Response_SubscribeAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SubscribeAck) ProtoMessage() {}

func (x *Response_SubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SubscribeAck.ProtoReflect.Descriptor instead.
func (*Response_SubscribeAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 4}
}

type Response_SubscribeNotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_SubscribeNotAck) Reset() {
	*x = Response_SubscribeNotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SubscribeNotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SubscribeNotAck) ProtoMessage() {}

func (x *Response_SubscribeNotAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SubscribeNotAck.ProtoReflect.Descriptor instead.
func (*Response_SubscribeNotAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Response_SubscribeNotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_SnapshotStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *Response_SnapshotStarted) Reset() {
	*x = Response_SnapshotStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SnapshotStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SnapshotStarted) ProtoMessage() {}

func (x *Response_SnapshotStarted) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SnapshotStarted.ProtoReflect.Descriptor instead.
func (*Response_SnapshotStarted) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Response_SnapshotStarted) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Response_SnapshotNotStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic  string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_SnapshotNotStarted) Reset() {
	*x = Response_SnapshotNotStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SnapshotNotStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SnapshotNotStarted) ProtoMessage() {}

func (x *Response_SnapshotNotStarted) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SnapshotNotStarted.ProtoReflect.Descriptor instead.
func (*Response_SnapshotNotStarted) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Response_SnapshotNotStarted) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_SnapshotNotStarted) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_SnapshotFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic      string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	SnapshotId string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FromTime   string `protobuf:"bytes,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime     string `protobuf:"bytes,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
}

func (x *Response_SnapshotFinished) Reset() {
	*x = Response_SnapshotFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SnapshotFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SnapshotFinished) ProtoMessage() {}

func (x *Response_SnapshotFinished) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SnapshotFinished.ProtoReflect.Descriptor instead.
func (*Response_SnapshotFinished) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Response_SnapshotFinished) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_SnapshotFinished) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Response_SnapshotFinished) GetFromTime() string {
	if x != nil {
		return x.FromTime
	}
	return ""
}

func (x *Response_SnapshotFinished) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

type Response_SnapshotNotFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic  string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_SnapshotNotFinished) Reset() {
	*x = Response_SnapshotNotFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SnapshotNotFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SnapshotNotFinished) ProtoMessage() {}

func (x *Response_SnapshotNotFinished) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SnapshotNotFinished.ProtoReflect.Descriptor instead.
func (*Response_SnapshotNotFinished) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Response_SnapshotNotFinished) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_SnapshotNotFinished) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_InvalidateGdprAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	GdprId   string `protobuf:"bytes,3,opt,name=gdpr_id,json=gdprId,proto3" json:"gdpr_id,omitempty"`
}

func (x *Response_InvalidateGdprAck) Reset() {
	*x = Response_InvalidateGdprAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_InvalidateGdprAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_InvalidateGdprAck) ProtoMessage() {}

func (x *Response_InvalidateGdprAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_InvalidateGdprAck.ProtoReflect.Descriptor instead.
func (*Response_InvalidateGdprAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Response_InvalidateGdprAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Response_InvalidateGdprAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_InvalidateGdprAck) GetGdprId() string {
	if x != nil {
		return x.GdprId
	}
	return ""
}

type Response_InvalidateGdprNotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	GdprId   string `protobuf:"bytes,3,opt,name=gdpr_id,json=gdprId,proto3" json:"gdpr_id,omitempty"`
	Reason   string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_InvalidateGdprNotAck) Reset() {
	*x = Response_InvalidateGdprNotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_InvalidateGdprNotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_InvalidateGdprNotAck) ProtoMessage() {}

func (x *Response_InvalidateGdprNotAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_InvalidateGdprNotAck.ProtoReflect.Descriptor instead.
func (*Response_InvalidateGdprNotAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Response_InvalidateGdprNotAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Response_InvalidateGdprNotAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_InvalidateGdprNotAck) GetGdprId() string {
	if x != nil {
		return x.GdprId
	}
	return ""
}

func (x *Response_InvalidateGdprNotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_IntroduceGdprOnFieldStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *Response_IntroduceGdprOnFieldStarted) Reset() {
	*x = Response_IntroduceGdprOnFieldStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_IntroduceGdprOnFieldStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_IntroduceGdprOnFieldStarted) ProtoMessage() {}

func (x *Response_IntroduceGdprOnFieldStarted) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_IntroduceGdprOnFieldStarted.ProtoReflect.Descriptor instead.
func (*Response_IntroduceGdprOnFieldStarted) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Response_IntroduceGdprOnFieldStarted) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Response_IntroduceGdprOnFieldNotStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic  string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_IntroduceGdprOnFieldNotStarted) Reset() {
	*x = Response_IntroduceGdprOnFieldNotStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_IntroduceGdprOnFieldNotStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_IntroduceGdprOnFieldNotStarted) ProtoMessage() {}

func (x *Response_IntroduceGdprOnFieldNotStarted) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_IntroduceGdprOnFieldNotStarted.ProtoReflect.Descriptor instead.
func (*Response_IntroduceGdprOnFieldNotStarted) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Response_IntroduceGdprOnFieldNotStarted) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_IntroduceGdprOnFieldNotStarted) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Response_IntroduceGdprOnFieldFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *Response_IntroduceGdprOnFieldFinished) Reset() {
	*x = Response_IntroduceGdprOnFieldFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_IntroduceGdprOnFieldFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_IntroduceGdprOnFieldFinished) ProtoMessage() {}

func (x *Response_IntroduceGdprOnFieldFinished) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_IntroduceGdprOnFieldFinished.ProtoReflect.Descriptor instead.
func (*Response_IntroduceGdprOnFieldFinished) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Response_IntroduceGdprOnFieldFinished) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Response_IntroduceGdprOnFieldNotFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic  string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response_IntroduceGdprOnFieldNotFinished) Reset() {
	*x = Response_IntroduceGdprOnFieldNotFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_response_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_IntroduceGdprOnFieldNotFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_IntroduceGdprOnFieldNotFinished) ProtoMessage() {}

func (x *Response_IntroduceGdprOnFieldNotFinished) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_response_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_IntroduceGdprOnFieldNotFinished.ProtoReflect.Descriptor instead.
func (*Response_IntroduceGdprOnFieldNotFinished) Descriptor() ([]byte, []int) {
	return file_clientchannel_response_proto_rawDescGZIP(), []int{0, 15}
}

func (x *Response_IntroduceGdprOnFieldNotFinished) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Response_IntroduceGdprOnFieldNotFinished) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_clientchannel_response_proto protoreflect.FileDescriptor

var file_clientchannel_response_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x19, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x14, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x41,
	0x63, 0x6b, 0x12, 0x46, 0x0a, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x61,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0a,
	0x69, 0x6e, 0x69, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x45, 0x0a, 0x0b, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63,
	0x6b, 0x12, 0x4f, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x41,
	0x63, 0x6b, 0x12, 0x4b, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f,
	0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x63, 0x6b, 0x48,
	0x00, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x63, 0x6b, 0x12,
	0x55, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74,
	0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x54, 0x0a, 0x10, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x5e, 0x0a, 0x14,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x57, 0x0a, 0x11,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x10, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x61, 0x0a, 0x15, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x13, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4e, 0x6f, 0x74,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x5b, 0x0a, 0x13, 0x69, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x61, 0x63, 0x6b, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x41, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64,
	0x70, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x65, 0x0a, 0x17, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x63, 0x6b,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4e, 0x6f,
	0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x14, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x7b, 0x0a, 0x1f,
	0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x6f,
	0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x1b, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x85, 0x01, 0x0a, 0x23, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x6f, 0x6e, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x1e, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72,
	0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x7e, 0x0a, 0x20, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x67,
	0x64, 0x70, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x66, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64,
	0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x1c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64,
	0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x12, 0x88, 0x01, 0x0a, 0x24, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x5f,
	0x67, 0x64, 0x70, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x6f,
	0x74, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x37, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f,
	0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x1f, 0x69, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x6f, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x1a, 0x09, 0x0a, 0x07,
	0x49, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x6b, 0x1a, 0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x4e,
	0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x38, 0x0a,
	0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x53, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x0e, 0x0a, 0x0c,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x63, 0x6b, 0x1a, 0x29, 0x0a, 0x0f,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x27, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x1a, 0x42, 0x0a, 0x12, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x7f, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x6f, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x43, 0x0a, 0x13, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x4e, 0x6f, 0x74, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x5f, 0x0a, 0x11, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x41, 0x63, 0x6b, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x64, 0x70, 0x72, 0x49, 0x64, 0x1a, 0x7a, 0x0a, 0x14, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4e, 0x6f, 0x74,
	0x41, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x64, 0x70, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x33, 0x0a, 0x1b, 0x49, 0x6e, 0x74, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x1a, 0x4e, 0x0a, 0x1e,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x34, 0x0a, 0x1c,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x1a, 0x4f, 0x0a, 0x1f, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47,
	0x64, 0x70, 0x72, 0x4f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_clientchannel_response_proto_rawDescOnce sync.Once
	file_clientchannel_response_proto_rawDescData = file_clientchannel_response_proto_rawDesc
)

func file_clientchannel_response_proto_rawDescGZIP() []byte {
	file_clientchannel_response_proto_rawDescOnce.Do(func() {
		file_clientchannel_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientchannel_response_proto_rawDescData)
	})
	return file_clientchannel_response_proto_rawDescData
}

var file_clientchannel_response_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_clientchannel_response_proto_goTypes = []interface{}{
	(*Response)(nil),                                 // 0: clientchannel.Response
	(*Response_InitAck)(nil),                         // 1: clientchannel.Response.InitAck
	(*Response_InitNotAck)(nil),                      // 2: clientchannel.Response.InitNotAck
	(*Response_PublishAck)(nil),                      // 3: clientchannel.Response.PublishAck
	(*Response_PublishNotAck)(nil),                   // 4: clientchannel.Response.PublishNotAck
	(*Response_SubscribeAck)(nil),                    // 5: clientchannel.Response.SubscribeAck
	(*Response_SubscribeNotAck)(nil),                 // 6: clientchannel.Response.SubscribeNotAck
	(*Response_SnapshotStarted)(nil),                 // 7: clientchannel.Response.SnapshotStarted
	(*Response_SnapshotNotStarted)(nil),              // 8: clientchannel.Response.SnapshotNotStarted
	(*Response_SnapshotFinished)(nil),                // 9: clientchannel.Response.SnapshotFinished
	(*Response_SnapshotNotFinished)(nil),             // 10: clientchannel.Response.SnapshotNotFinished
	(*Response_InvalidateGdprAck)(nil),               // 11: clientchannel.Response.InvalidateGdprAck
	(*Response_InvalidateGdprNotAck)(nil),            // 12: clientchannel.Response.InvalidateGdprNotAck
	(*Response_IntroduceGdprOnFieldStarted)(nil),     // 13: clientchannel.Response.IntroduceGdprOnFieldStarted
	(*Response_IntroduceGdprOnFieldNotStarted)(nil),  // 14: clientchannel.Response.IntroduceGdprOnFieldNotStarted
	(*Response_IntroduceGdprOnFieldFinished)(nil),    // 15: clientchannel.Response.IntroduceGdprOnFieldFinished
	(*Response_IntroduceGdprOnFieldNotFinished)(nil), // 16: clientchannel.Response.IntroduceGdprOnFieldNotFinished
	(*PublishEventEnvelope)(nil),                     // 17: PublishEventEnvelope
}
var file_clientchannel_response_proto_depIdxs = []int32{
	17, // 0: clientchannel.Response.event:type_name -> PublishEventEnvelope
	1,  // 1: clientchannel.Response.init_ack:type_name -> clientchannel.Response.InitAck
	2,  // 2: clientchannel.Response.init_not_ack:type_name -> clientchannel.Response.InitNotAck
	3,  // 3: clientchannel.Response.publish_ack:type_name -> clientchannel.Response.PublishAck
	4,  // 4: clientchannel.Response.publish_not_ack:type_name -> clientchannel.Response.PublishNotAck
	5,  // 5: clientchannel.Response.subscribe_ack:type_name -> clientchannel.Response.SubscribeAck
	6,  // 6: clientchannel.Response.subscribe_not_ack:type_name -> clientchannel.Response.SubscribeNotAck
	7,  // 7: clientchannel.Response.snapshot_started:type_name -> clientchannel.Response.SnapshotStarted
	8,  // 8: clientchannel.Response.snapshot_not_started:type_name -> clientchannel.Response.SnapshotNotStarted
	9,  // 9: clientchannel.Response.snapshot_finished:type_name -> clientchannel.Response.SnapshotFinished
	10, // 10: clientchannel.Response.snapshot_not_finished:type_name -> clientchannel.Response.SnapshotNotFinished
	11, // 11: clientchannel.Response.invalidate_gdpr_ack:type_name -> clientchannel.Response.InvalidateGdprAck
	12, // 12: clientchannel.Response.invalidate_gdpr_not_ack:type_name -> clientchannel.Response.InvalidateGdprNotAck
	13, // 13: clientchannel.Response.introduce_gdpr_on_field_started:type_name -> clientchannel.Response.IntroduceGdprOnFieldStarted
	14, // 14: clientchannel.Response.introduce_gdpr_on_field_not_started:type_name -> clientchannel.Response.IntroduceGdprOnFieldNotStarted
	15, // 15: clientchannel.Response.introduce_gdpr_on_field_finished:type_name -> clientchannel.Response.IntroduceGdprOnFieldFinished
	16, // 16: clientchannel.Response.introduce_gdpr_on_field_not_finished:type_name -> clientchannel.Response.IntroduceGdprOnFieldNotFinished
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_clientchannel_response_proto_init() }
func file_clientchannel_response_proto_init() {
	if File_clientchannel_response_proto != nil {
		return
	}
	file_clientchannel_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_clientchannel_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_InitAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_InitNotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_PublishAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_PublishNotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SubscribeAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SubscribeNotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SnapshotStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SnapshotNotStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SnapshotFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SnapshotNotFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_InvalidateGdprAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_InvalidateGdprNotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_IntroduceGdprOnFieldStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_IntroduceGdprOnFieldNotStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_IntroduceGdprOnFieldFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_response_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_IntroduceGdprOnFieldNotFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_clientchannel_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Response_Event)(nil),
		(*Response_InitAck_)(nil),
		(*Response_InitNotAck_)(nil),
		(*Response_PublishAck_)(nil),
		(*Response_PublishNotAck_)(nil),
		(*Response_SubscribeAck_)(nil),
		(*Response_SubscribeNotAck_)(nil),
		(*Response_SnapshotStarted_)(nil),
		(*Response_SnapshotNotStarted_)(nil),
		(*Response_SnapshotFinished_)(nil),
		(*Response_SnapshotNotFinished_)(nil),
		(*Response_InvalidateGdprAck_)(nil),
		(*Response_InvalidateGdprNotAck_)(nil),
		(*Response_IntroduceGdprOnFieldStarted_)(nil),
		(*Response_IntroduceGdprOnFieldNotStarted_)(nil),
		(*Response_IntroduceGdprOnFieldFinished_)(nil),
		(*Response_IntroduceGdprOnFieldNotFinished_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientchannel_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientchannel_response_proto_goTypes,
		DependencyIndexes: file_clientchannel_response_proto_depIdxs,
		MessageInfos:      file_clientchannel_response_proto_msgTypes,
	}.Build()
	File_clientchannel_response_proto = out.File
	file_clientchannel_response_proto_rawDesc = nil
	file_clientchannel_response_proto_goTypes = nil
	file_clientchannel_response_proto_depIdxs = nil
}
