// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: clientchannel/request.proto

package clientchannel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Request_Init
	//	*Request_Publish
	//	*Request_Subscribe
	//	*Request_InvalidateGdpr
	//	*Request_Snapshot
	//	*Request_EventAck_
	//	*Request_EventNotAck_
	Payload isRequest_Payload `protobuf_oneof:"payload"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetPayload() isRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Request) GetInit() *Request_InitAction {
	if x, ok := x.GetPayload().(*Request_Init); ok {
		return x.Init
	}
	return nil
}

func (x *Request) GetPublish() *Request_PublishAction {
	if x, ok := x.GetPayload().(*Request_Publish); ok {
		return x.Publish
	}
	return nil
}

func (x *Request) GetSubscribe() *Request_SubscribeAction {
	if x, ok := x.GetPayload().(*Request_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *Request) GetInvalidateGdpr() *Request_InvalidateGdprAction {
	if x, ok := x.GetPayload().(*Request_InvalidateGdpr); ok {
		return x.InvalidateGdpr
	}
	return nil
}

func (x *Request) GetSnapshot() *Request_SnapshotAction {
	if x, ok := x.GetPayload().(*Request_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *Request) GetEventAck() *Request_EventAck {
	if x, ok := x.GetPayload().(*Request_EventAck_); ok {
		return x.EventAck
	}
	return nil
}

func (x *Request) GetEventNotAck() *Request_EventNotAck {
	if x, ok := x.GetPayload().(*Request_EventNotAck_); ok {
		return x.EventNotAck
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Init struct {
	Init *Request_InitAction `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type Request_Publish struct {
	Publish *Request_PublishAction `protobuf:"bytes,2,opt,name=publish,proto3,oneof"`
}

type Request_Subscribe struct {
	Subscribe *Request_SubscribeAction `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type Request_InvalidateGdpr struct {
	InvalidateGdpr *Request_InvalidateGdprAction `protobuf:"bytes,5,opt,name=invalidate_gdpr,json=invalidateGdpr,proto3,oneof"`
}

type Request_Snapshot struct {
	Snapshot *Request_SnapshotAction `protobuf:"bytes,6,opt,name=snapshot,proto3,oneof"`
}

type Request_EventAck_ struct {
	EventAck *Request_EventAck `protobuf:"bytes,7,opt,name=event_ack,json=eventAck,proto3,oneof"`
}

type Request_EventNotAck_ struct {
	EventNotAck *Request_EventNotAck `protobuf:"bytes,8,opt,name=event_not_ack,json=eventNotAck,proto3,oneof"`
}

func (*Request_Init) isRequest_Payload() {}

func (*Request_Publish) isRequest_Payload() {}

func (*Request_Subscribe) isRequest_Payload() {}

func (*Request_InvalidateGdpr) isRequest_Payload() {}

func (*Request_Snapshot) isRequest_Payload() {}

func (*Request_EventAck_) isRequest_Payload() {}

func (*Request_EventNotAck_) isRequest_Payload() {}

type Request_InitAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId      string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SubscriberId string `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
}

func (x *Request_InitAction) Reset() {
	*x = Request_InitAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_InitAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_InitAction) ProtoMessage() {}

func (x *Request_InitAction) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_InitAction.ProtoReflect.Descriptor instead.
func (*Request_InitAction) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_InitAction) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Request_InitAction) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type Request_PublishAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic           string           `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PublishActionId string           `protobuf:"bytes,2,opt,name=publish_action_id,json=publishActionId,proto3" json:"publish_action_id,omitempty"`
	Events          []*EventEnvelope `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Request_PublishAction) Reset() {
	*x = Request_PublishAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_PublishAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_PublishAction) ProtoMessage() {}

func (x *Request_PublishAction) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_PublishAction.ProtoReflect.Descriptor instead.
func (*Request_PublishAction) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Request_PublishAction) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request_PublishAction) GetPublishActionId() string {
	if x != nil {
		return x.PublishActionId
	}
	return ""
}

func (x *Request_PublishAction) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type Request_SubscribeAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludedTopics []string `protobuf:"bytes,1,rep,name=included_topics,json=includedTopics,proto3" json:"included_topics,omitempty"`
	ExcludedTopics []string `protobuf:"bytes,2,rep,name=excluded_topics,json=excludedTopics,proto3" json:"excluded_topics,omitempty"`
}

func (x *Request_SubscribeAction) Reset() {
	*x = Request_SubscribeAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_SubscribeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SubscribeAction) ProtoMessage() {}

func (x *Request_SubscribeAction) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SubscribeAction.ProtoReflect.Descriptor instead.
func (*Request_SubscribeAction) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Request_SubscribeAction) GetIncludedTopics() []string {
	if x != nil {
		return x.IncludedTopics
	}
	return nil
}

func (x *Request_SubscribeAction) GetExcludedTopics() []string {
	if x != nil {
		return x.ExcludedTopics
	}
	return nil
}

type Request_SnapshotAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic  string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ToTime string `protobuf:"bytes,2,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
}

func (x *Request_SnapshotAction) Reset() {
	*x = Request_SnapshotAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_SnapshotAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SnapshotAction) ProtoMessage() {}

func (x *Request_SnapshotAction) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SnapshotAction.ProtoReflect.Descriptor instead.
func (*Request_SnapshotAction) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Request_SnapshotAction) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request_SnapshotAction) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

type Request_InvalidateGdprAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	GdprId   string `protobuf:"bytes,3,opt,name=gdpr_id,json=gdprId,proto3" json:"gdpr_id,omitempty"`
}

func (x *Request_InvalidateGdprAction) Reset() {
	*x = Request_InvalidateGdprAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_InvalidateGdprAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_InvalidateGdprAction) ProtoMessage() {}

func (x *Request_InvalidateGdprAction) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_InvalidateGdprAction.ProtoReflect.Descriptor instead.
func (*Request_InvalidateGdprAction) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Request_InvalidateGdprAction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Request_InvalidateGdprAction) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request_InvalidateGdprAction) GetGdprId() string {
	if x != nil {
		return x.GdprId
	}
	return ""
}

type Request_EventAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	EventId  string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *Request_EventAck) Reset() {
	*x = Request_EventAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_EventAck) ProtoMessage() {}

func (x *Request_EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_EventAck.ProtoReflect.Descriptor instead.
func (*Request_EventAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Request_EventAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Request_EventAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request_EventAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type Request_EventNotAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	EventId  string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason   string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Request_EventNotAck) Reset() {
	*x = Request_EventNotAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientchannel_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_EventNotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_EventNotAck) ProtoMessage() {}

func (x *Request_EventNotAck) ProtoReflect() protoreflect.Message {
	mi := &file_clientchannel_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_EventNotAck.ProtoReflect.Descriptor instead.
func (*Request_EventNotAck) Descriptor() ([]byte, []int) {
	return file_clientchannel_request_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Request_EventNotAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Request_EventNotAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request_EventNotAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Request_EventNotAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_clientchannel_request_proto protoreflect.FileDescriptor

var file_clientchannel_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x19, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x40, 0x0a, 0x07,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x46,
	0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x64, 0x70, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e,
	0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x12, 0x43,
	0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x6b,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x6b, 0x12, 0x48, 0x0a, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x61, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00,
	0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x1a, 0x4c, 0x0a,
	0x0a, 0x49, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x79, 0x0a, 0x0d, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x63, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x5f, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x1a, 0x3f, 0x0a, 0x0e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x62, 0x0a, 0x14,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x64, 0x70, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x64, 0x70, 0x72, 0x49, 0x64,
	0x1a, 0x58, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x73, 0x0a, 0x0b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_clientchannel_request_proto_rawDescOnce sync.Once
	file_clientchannel_request_proto_rawDescData = file_clientchannel_request_proto_rawDesc
)

func file_clientchannel_request_proto_rawDescGZIP() []byte {
	file_clientchannel_request_proto_rawDescOnce.Do(func() {
		file_clientchannel_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientchannel_request_proto_rawDescData)
	})
	return file_clientchannel_request_proto_rawDescData
}

var file_clientchannel_request_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_clientchannel_request_proto_goTypes = []interface{}{
	(*Request)(nil),                      // 0: clientchannel.Request
	(*Request_InitAction)(nil),           // 1: clientchannel.Request.InitAction
	(*Request_PublishAction)(nil),        // 2: clientchannel.Request.PublishAction
	(*Request_SubscribeAction)(nil),      // 3: clientchannel.Request.SubscribeAction
	(*Request_SnapshotAction)(nil),       // 4: clientchannel.Request.SnapshotAction
	(*Request_InvalidateGdprAction)(nil), // 5: clientchannel.Request.InvalidateGdprAction
	(*Request_EventAck)(nil),             // 6: clientchannel.Request.EventAck
	(*Request_EventNotAck)(nil),          // 7: clientchannel.Request.EventNotAck
	(*EventEnvelope)(nil),                // 8: EventEnvelope
}
var file_clientchannel_request_proto_depIdxs = []int32{
	1, // 0: clientchannel.Request.init:type_name -> clientchannel.Request.InitAction
	2, // 1: clientchannel.Request.publish:type_name -> clientchannel.Request.PublishAction
	3, // 2: clientchannel.Request.subscribe:type_name -> clientchannel.Request.SubscribeAction
	5, // 3: clientchannel.Request.invalidate_gdpr:type_name -> clientchannel.Request.InvalidateGdprAction
	4, // 4: clientchannel.Request.snapshot:type_name -> clientchannel.Request.SnapshotAction
	6, // 5: clientchannel.Request.event_ack:type_name -> clientchannel.Request.EventAck
	7, // 6: clientchannel.Request.event_not_ack:type_name -> clientchannel.Request.EventNotAck
	8, // 7: clientchannel.Request.PublishAction.events:type_name -> EventEnvelope
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_clientchannel_request_proto_init() }
func file_clientchannel_request_proto_init() {
	if File_clientchannel_request_proto != nil {
		return
	}
	file_clientchannel_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_clientchannel_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_InitAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_PublishAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_SubscribeAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_SnapshotAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_InvalidateGdprAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_EventAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientchannel_request_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_EventNotAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_clientchannel_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_Init)(nil),
		(*Request_Publish)(nil),
		(*Request_Subscribe)(nil),
		(*Request_InvalidateGdpr)(nil),
		(*Request_Snapshot)(nil),
		(*Request_EventAck_)(nil),
		(*Request_EventNotAck_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientchannel_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientchannel_request_proto_goTypes,
		DependencyIndexes: file_clientchannel_request_proto_depIdxs,
		MessageInfos:      file_clientchannel_request_proto_msgTypes,
	}.Build()
	File_clientchannel_request_proto = out.File
	file_clientchannel_request_proto_rawDesc = nil
	file_clientchannel_request_proto_goTypes = nil
	file_clientchannel_request_proto_depIdxs = nil
}
